all:
  children:
    managers:
      hosts:
        manager:
    workers:
      hosts:
        worker-1:
  vars:
    ansible_user: harryvolker
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'